config/routes.rb
Rails.application.routes.draw do
  
  resources :notifications
  resources :dashboards
  resources :forms do
    collection do
        get :critical_forms
        get :high_forms
        get :medium_forms
        get :low_forms
        get :department_a_forms
        get :department_b_forms
        get :department_c_forms
    end
  end

  root 'forms#index'
  
  devise_for :users
  resources :users
  resources :roles

  end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def index
    @forms_count = Form.all.count
    @users_count = User.all.count
    @critical_forms_count = Form.where(category_level: AppConstants::CRITICAL).count
    @high_forms_count = Form.where(category_level: AppConstants::HIGH).count
    @medium_forms_count = Form.where(category_level: AppConstants::MEDIUM).count
    @low_forms_count = Form.where(category_level: AppConstants::LOW).count
    @department_a_count = Form.where(department: AppConstants::DEPARTMENT_A).count
    @department_b_count = Form.where(department: AppConstants::DEPARTMENT_B).count
    @department_c_count = Form.where(department: AppConstants::DEPARTMENT_C).count
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_critical_forms_block.html.erb
<div class="col-md-3 col-sm-6 spacing-bottom-sm spacing-bottom">
  <div class="tiles added-margin <%= "#{block_color}"%>">
    <div class="tiles-body">
      <div class="heading"><%= link_to title,critical_forms_forms_path, class: 'href-heading_size' %></div>
      <div class="">
        <span class="animate-number"><%= title_1 %>:</span>
        <span class="animate-number"><%= count_1 %></span>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_department_a_block.html.erb
<div class="col-md-3 col-sm-6 spacing-bottom-sm spacing-bottom">
  <div class="tiles added-margin <%= "#{block_color}"%>">
    <div class="tiles-body">
      <div class="heading"><%= link_to title,department_a_forms_forms_path, class: 'href-heading_size' %></div>
      <div class="">
        <span class="animate-number"><%= title_1 %>:</span>
        <span class="animate-number"><%= count_1 %></span>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_department_b_block.html.erb
<div class="col-md-3 col-sm-6 spacing-bottom-sm spacing-bottom">
  <div class="tiles added-margin <%= "#{block_color}"%>">
    <div class="tiles-body">
      <div class="heading"><%= link_to title,department_b_forms_forms_path, class: 'href-heading_size' %></div>
      <div class="">
        <span class="animate-number"><%= title_1 %>:</span>
        <span class="animate-number"><%= count_1 %></span>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_department_c_block.html.erb
<div class="col-md-3 col-sm-6 spacing-bottom-sm spacing-bottom">
  <div class="tiles added-margin <%= "#{block_color}"%>">
    <div class="tiles-body">
      <div class="heading"><%= link_to title,department_c_forms_forms_path, class: 'href-heading_size' %></div>
      <div class="">
        <span class="animate-number"><%= title_1 %>:</span>
        <span class="animate-number"><%= count_1 %></span>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_forms_block.html.erb
<div class="col-md-3 col-sm-6 spacing-bottom-sm spacing-bottom">
  <div class="tiles added-margin <%= "#{block_color}"%>">
    <div class="tiles-body">
      <div class="heading"><%= link_to title,forms_path, class: 'href-heading_size' %></div>
      <div class="">
        <span class="animate-number"><%= title_1 %>:</span>
        <span class="animate-number"><%= count_1 %></span>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_high_forms_block.html.erb
<div class="col-md-3 col-sm-6 spacing-bottom-sm spacing-bottom">
  <div class="tiles added-margin <%= "#{block_color}"%>">
    <div class="tiles-body">
      <div class="heading"><%= link_to title,high_forms_forms_path, class: 'href-heading_size' %></div>
      <div class="">
        <span class="animate-number"><%= title_1 %>:</span>
        <span class="animate-number"><%= count_1 %></span>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_low_forms_block.html.erb
<div class="col-md-3 col-sm-6 spacing-bottom-sm spacing-bottom">
  <div class="tiles added-margin <%= "#{block_color}"%>">
    <div class="tiles-body">
      <div class="heading"><%= link_to title,low_forms_forms_path, class: 'href-heading_size' %></div>
      <div class="">
        <span class="animate-number"><%= title_1 %>:</span>
        <span class="animate-number"><%= count_1 %></span>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_medium_forms_block.html.erb
<div class="col-md-3 col-sm-6 spacing-bottom-sm spacing-bottom">
  <div class="tiles added-margin <%= "#{block_color}"%>">
    <div class="tiles-body">
      <div class="heading"><%= link_to title,medium_forms_forms_path, class: 'href-heading_size' %></div>
      <div class="">
        <span class="animate-number"><%= title_1 %>:</span>
        <span class="animate-number"><%= count_1 %></span>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_report_block.html.erb
<div class="col-md-3 col-sm-6 spacing-bottom-sm spacing-bottom">
  <div class="tiles added-margin <%= "#{block_color}"%>">
    <div class="tiles-body">
      <div class="heading"><%= link_to title,forms_path, class: 'href-heading_size' %></div>
      <div class="">
        <span class="animate-number"><%= title_1 %>:</span>
        <span class="animate-number"><%= count_1 %></span>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_report_block1.html.erb
<div class="col-md-3 col-sm-6 spacing-bottom-sm spacing-bottom">
  <div class="tiles added-margin <%= "#{block_color}"%>">
    <div class="tiles-body">
      <div class="heading"><%= link_to title,forms_path, class: 'href-heading_size' %></div>
      <div class="">
        <span class="animate-number"><%= title_1 %>:</span>
        <span class="animate-number"><%= count_1 %></span>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_users_block.html.erb
<div class="col-md-3 col-sm-6 spacing-bottom-sm spacing-bottom">
  <div class="tiles added-margin <%= "#{block_color}"%>">
    <div class="tiles-body">
      <div class="heading"><%= link_to title,users_path, class: 'href-heading_size' %></div>
      <div class="">
        <span class="animate-number"><%= title_1 %>:</span>
        <span class="animate-number"><%= count_1 %></span>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/index.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Dashboard</h2>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <!--<div id="container">-->
          <!--<div class="row 2col">-->
            <!--<%#= render 'forms_block', block_color: 'blue', title: 'Forms', title_1: 'Tot. forms', count_1: @forms_count %>-->
            <!--<%#= render 'users_block', block_color: 'red', title: 'Users', title_1: 'Tot. users', count_1: @users_count %>-->
          <!--</div>-->
    <!--</div>-->

    <div class="page-title">
      <h3>Category</h3>
    </div>
    <div id="container">
      <div class="row 2col">
        <%= render 'critical_forms_block', block_color: 'blue', title: 'Critical Forms', title_1: 'Tot. forms', count_1: @critical_forms_count %>
        <%= render 'high_forms_block', block_color: 'red', title: 'High Forms', title_1: 'Tot. forms', count_1: @high_forms_count %>
        <%= render 'medium_forms_block', block_color: 'green', title: 'Medium Forms', title_1: 'Tot. forms', count_1: @medium_forms_count %>
        <%= render 'low_forms_block', block_color: 'purple', title: 'Low Forms', title_1: 'Tot. forms', count_1: @low_forms_count %>
      </div>
    </div>

    <div class="page-title">
      <h3>Department</h3>
    </div>
    <% if @current_user_role == AppConstants::ADMIN %>
      <div id="container">
        <div class="row 2col">
          <%= render 'department_a_block', block_color: 'blue', title: 'Department A', title_1: 'Tot. department forms', count_1: @department_a_count %>
          <%= render 'department_b_block', block_color: 'red', title: 'Department B', title_1: 'Tot. department forms', count_1: @department_b_count %>
          <%= render 'department_c_block', block_color: 'green', title: 'Department C', title_1: 'Tot. department forms', count_1: @department_c_count %>
        </div>
      </div>
    <% end %>
    <% if @current_user_role == AppConstants::TEAM_LEADER %>
      <div id="container">
        <div class="row 2col">
          <%= render 'department_a_block', block_color: 'blue', title: 'Department A', title_1: 'Tot. department forms', count_1: @department_a_count %>
          <%= render 'department_b_block', block_color: 'red', title: 'Department B', title_1: 'Tot. department forms', count_1: @department_b_count %>
        </div>
      </div>
    <% end %>
    <% if @current_user_role == AppConstants::USER || @current_user_role == AppConstants::SPECIALIST %>
      <div id="container">
        <div class="row 2col">
          <%= render 'department_a_block', block_color: 'blue', title: 'Department A', title_1: 'Tot. department forms', count_1: @department_a_count %>
        </div>
      </div>
    <% end %>
  </div>
</div>