config/routes.rb
Rails.application.routes.draw do
  
  resources :notifications
  resources :dashboards
  resources :forms do
    collection do
        get :critical_forms
        get :high_forms
        get :medium_forms
        get :low_forms
        get :department_a_forms
        get :department_b_forms
        get :department_c_forms
    end
  end

  root 'forms#index'
  
  devise_for :users
  resources :users
  resources :roles

  end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  def index
      @forms = Form.all
  end

  def show
  end

  def new
    @form = Form.new
  end

  def edit
  end

  def create
    # binding.pry
    @form = Form.new(form_params)
    if @form.valid?
      respond_to do |format|
        if @form.save
          format.html { redirect_to @form, notice: 'Form was successfully created.' }
        else
          format.html { render :new }
        end
      end
    else
      render :new
    end
  end

  def update
    # binding.pry
    respond_to do |format|
        if @form.update(form_params)
          format.html { redirect_to @form, notice: 'Form was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
  end

  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
    end
  end

  def critical_forms
    @forms = Form.where(category_level: AppConstants::CRITICAL)
  end

  def high_forms
    @forms = Form.where(category_level: AppConstants::HIGH)
  end

  def medium_forms
    @forms = Form.where(category_level: AppConstants::MEDIUM)
  end

  def low_forms
    @forms = Form.where(category_level: AppConstants::LOW)
  end

  def department_a_forms
    @forms = Form.where(department: AppConstants::DEPARTMENT_A)
  end

  def department_b_forms
    @forms = Form.where(department: AppConstants::DEPARTMENT_B)
  end

  def department_c_forms
    @forms = Form.where(department: AppConstants::DEPARTMENT_C)
  end

  private
    def set_form
      @form = Form.find(params[:id])
    end

    def form_params
      params.require(:form).permit(:department, :category, :date_started, :date_completed,  :summary_of_problem, :impact, :applicable_to_other_areas, :user_id, :solution_applied, :category_level,:updated_by,:completed_by,:is_complete)
    end
end

app/helpers/api/v1/forms_helper.rb
module Api::V1::FormsHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= simple_form_for(@form) do |f| %>

  <div class="form-inputs container">
    <div class="col-lg-6 col-md-12 col-sm-12">
      <%= f.input :department,collection: [['Department A', 'Department A'] ,['Department B', 'Department B'], ['Department C', 'Department C']], prompt: "Select Department", :input_html => { :class => 'input-field' } %>
      <%= f.collection_radio_buttons :category, [['Lead', 'Lead'] ,['Non-Lead', 'Non-Lead']],:first, :last %>
      <%= f.input :date_started, :input_html => { :class => 'datepicker input-field' } %>
      <%= f.input :date_completed, :input_html => { :class => 'datepicker input-field' } %>
      <%= f.input :category_level,collection: [['Critical', 'Critical'] ,['High', 'High'], ['Medium', 'Medium'], ['Low', 'Low']], prompt: "Select Category", :input_html => { :class => 'input-field' } %>
    </div>

    <div class="col-lg-6 col-md-12 col-sm-12">
      <%= f.input :summary_of_problem, :input_html => { :class => 'input-field' } %>
      <%= f.input :impact, :input_html => { :class => 'input-field' } %>
      <%= f.input :applicable_to_other_areas, :input_html => { :class => 'input-field' } %>
      <%= f.input :solution_applied, :input_html => { :class => 'input-field' } %>
      <%= f.input :user_id,:as => :hidden, :input_html => { :class => 'input-field', :value => current_user.id } %>
      <%= f.input :updated_by,:as => :hidden, :input_html => { :class => 'input-field', :value => current_user.id } %>
    </div >
  </div>


  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
    $('.datepicker').datepicker();
</script>

app/views/forms/critical_forms.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Froms</h2>
    <% if @current_user_role == AppConstants::ADMIN || @current_user_role == AppConstants::TEAM_LEADER %>
        <%= link_to 'New Form', new_form_path , class: 'btn btn-primary pull-right' %>
    <% end %>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <table class="table table-striped table-responsive" id="example">
      <thead>
      <tr>
        <th>Department</th>
        <th>Category</th>
        <th>Date started</th>
        <th>Date completed</th>
        <th>Summary of Problem</th>
        <th>Impact</th>
        <th>Applicable to Other Areas</th>
        <th>Solution Applied</th>
        <th>Level</th>
        <th>Created By</th>
        <th>Updated By</th>
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>
      <% @forms.each do |form| %>
          <tr>
            <td><%= form.department %></td>
            <td><%= form.category %></td>
            <td><%= form.date_started %></td>
            <td><%= form.date_completed %></td>
            <td><%= form.summary_of_problem %></td>
            <td><%= form.impact %></td>
            <td><%= form.applicable_to_other_areas %></td>
            <td><%= form.solution_applied %></td>
            <td><%= form.category_level %></td>
            <td><% id =form.user_id %><%=  User.find_by_id( id ).first_name %></td>
            <td><% id =form.updated_by %><%=  User.find_by_id( id ).first_name || 0 %></td>
            <td>
              <%= link_to 'Edit', edit_form_path(form), class: 'btn btn-info btn-xs' %>
              <% if @current_user_role == AppConstants::ADMIN || @current_user_role == AppConstants::TEAM_LEADER%>
                  <%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/forms/department_a_forms.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Froms</h2>
    <% if @current_user_role == AppConstants::ADMIN || @current_user_role == AppConstants::TEAM_LEADER %>
        <%= link_to 'New Form', new_form_path , class: 'btn btn-primary pull-right' %>
    <% end %>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <table class="table table-striped table-responsive" id="example">
      <thead>
      <tr>
        <th>Department</th>
        <th>Category</th>
        <th>Date started</th>
        <th>Date completed</th>
        <th>Summary of Problem</th>
        <th>Impact</th>
        <th>Applicable to Other Areas</th>
        <th>Solution Applied</th>
        <th>Level</th>
        <th>Created By</th>
        <th>Updated By</th>
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>
      <% @forms.each do |form| %>
          <tr>
            <td><%= form.department %></td>
            <td><%= form.category %></td>
            <td><%= form.date_started %></td>
            <td><%= form.date_completed %></td>
            <td><%= form.summary_of_problem %></td>
            <td><%= form.impact %></td>
            <td><%= form.applicable_to_other_areas %></td>
            <td><%= form.solution_applied %></td>
            <td><%= form.category_level %></td>
            <td><% id =form.user_id %><%=  User.find_by_id( id ).first_name %></td>
            <td><% id =form.updated_by %><%=  User.find_by_id( id ).first_name || 0 %></td>
            <td>
              <%= link_to 'Edit', edit_form_path(form), class: 'btn btn-info btn-xs' %>
              <% if @current_user_role == AppConstants::ADMIN || @current_user_role == AppConstants::TEAM_LEADER%>
                  <%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/forms/department_b_forms.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Froms</h2>
    <% if @current_user_role == AppConstants::ADMIN || @current_user_role == AppConstants::TEAM_LEADER %>
        <%= link_to 'New Form', new_form_path , class: 'btn btn-primary pull-right' %>
    <% end %>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <table class="table table-striped table-responsive" id="example">
      <thead>
      <tr>
        <th>Department</th>
        <th>Category</th>
        <th>Date started</th>
        <th>Date completed</th>
        <th>Summary of Problem</th>
        <th>Impact</th>
        <th>Applicable to Other Areas</th>
        <th>Solution Applied</th>
        <th>Level</th>
        <th>Created By</th>
        <th>Updated By</th>
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>
      <% @forms.each do |form| %>
          <tr>
            <td><%= form.department %></td>
            <td><%= form.category %></td>
            <td><%= form.date_started %></td>
            <td><%= form.date_completed %></td>
            <td><%= form.summary_of_problem %></td>
            <td><%= form.impact %></td>
            <td><%= form.applicable_to_other_areas %></td>
            <td><%= form.solution_applied %></td>
            <td><%= form.category_level %></td>
            <td><% id =form.user_id %><%=  User.find_by_id( id ).first_name %></td>
            <td><% id =form.updated_by %><%=  User.find_by_id( id ).first_name || 0 %></td>
            <td>
              <%= link_to 'Edit', edit_form_path(form), class: 'btn btn-info btn-xs' %>
              <% if @current_user_role == AppConstants::ADMIN || @current_user_role == AppConstants::TEAM_LEADER%>
                  <%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/forms/department_c_forms.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Froms</h2>
    <% if @current_user_role == AppConstants::ADMIN || @current_user_role == AppConstants::TEAM_LEADER %>
        <%= link_to 'New Form', new_form_path , class: 'btn btn-primary pull-right' %>
    <% end %>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <table class="table table-striped table-responsive" id="example">
      <thead>
      <tr>
        <th>Department</th>
        <th>Category</th>
        <th>Date started</th>
        <th>Date completed</th>
        <th>Summary of Problem</th>
        <th>Impact</th>
        <th>Applicable to Other Areas</th>
        <th>Solution Applied</th>
        <th>Level</th>
        <th>Created By</th>
        <th>Updated By</th>
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>
      <% @forms.each do |form| %>
          <tr>
            <td><%= form.department %></td>
            <td><%= form.category %></td>
            <td><%= form.date_started %></td>
            <td><%= form.date_completed %></td>
            <td><%= form.summary_of_problem %></td>
            <td><%= form.impact %></td>
            <td><%= form.applicable_to_other_areas %></td>
            <td><%= form.solution_applied %></td>
            <td><%= form.category_level %></td>
            <td><% id =form.user_id %><%=  User.find_by_id( id ).first_name %></td>
            <td><% id =form.updated_by %><%=  User.find_by_id( id ).first_name || 0 %></td>
            <td>
              <%= link_to 'Edit', edit_form_path(form), class: 'btn btn-info btn-xs' %>
              <% if @current_user_role == AppConstants::ADMIN || @current_user_role == AppConstants::TEAM_LEADER%>
                  <%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/forms/edit.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>New From</h2>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <%= simple_form_for(@form) do |f| %>

        <div class="form-inputs container">
          <div class="col-lg-6 col-md-12 col-sm-12">
            <%= f.input :department,collection: [['Department A', 'Department A'] ,['Department B', 'Department B'], ['Department C', 'Department C']], prompt: "Select Department", :input_html => { :class => 'input-field' } %>
            <%= f.collection_radio_buttons :category, [['Lead', 'Lead'] ,['Non-Lead', 'Non-Lead']],:first, :last %>
            <%= f.input :date_started, :input_html => { :class => 'datepicker input-field' } %>
            <%= f.input :date_completed, :input_html => { :class => 'datepicker input-field' } %>
            <%= f.input :category_level,collection: [['Critical', 'Critical'] ,['High', 'High'], ['Medium', 'Medium'], ['Low', 'Low']], prompt: "Select Category", :input_html => { :class => 'input-field' } %>
          </div>

          <div class="col-lg-6 col-md-12 col-sm-12">
            <%= f.input :summary_of_problem, :input_html => { :class => 'input-field' } %>
            <%= f.input :impact, :input_html => { :class => 'input-field' } %>
            <%= f.input :applicable_to_other_areas, :input_html => { :class => 'input-field' } %>
            <%= f.input :solution_applied, :input_html => { :class => 'input-field' } %>
            <%= f.input :user_id,:as => :hidden, :input_html => { :class => 'input-field' } %>
            <%= f.input :updated_by,:as => :hidden, :input_html => { :class => 'input-field', :value => current_user.id } %>
          </div >
        </div>


        <div class="form-actions">
          <%= f.button :submit, class: 'btn btn-primary' %>
        </div>
    <% end %>

    <script type="text/javascript" charset="utf-8">
        $('.datepicker').datepicker();
    </script>
  </div>
</div>

app/views/forms/high_forms.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Froms</h2>
    <% if @current_user_role == AppConstants::ADMIN || @current_user_role == AppConstants::TEAM_LEADER %>
        <%= link_to 'New Form', new_form_path , class: 'btn btn-primary pull-right' %>
    <% end %>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <table class="table table-striped table-responsive" id="example">
      <thead>
      <tr>
        <th>Department</th>
        <th>Category</th>
        <th>Date started</th>
        <th>Date completed</th>
        <th>Summary of Problem</th>
        <th>Impact</th>
        <th>Applicable to Other Areas</th>
        <th>Solution Applied</th>
        <th>Level</th>
        <th>Created By</th>
        <th>Updated By</th>
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>
      <% @forms.each do |form| %>
          <tr>
            <td><%= form.department %></td>
            <td><%= form.category %></td>
            <td><%= form.date_started %></td>
            <td><%= form.date_completed %></td>
            <td><%= form.summary_of_problem %></td>
            <td><%= form.impact %></td>
            <td><%= form.applicable_to_other_areas %></td>
            <td><%= form.solution_applied %></td>
            <td><%= form.category_level %></td>
            <td><% id =form.user_id %><%=  User.find_by_id( id ).first_name %></td>
            <td><% id =form.updated_by %><%=  User.find_by_id( id ).first_name || 0 %></td>
            <td>
              <%= link_to 'Edit', edit_form_path(form), class: 'btn btn-info btn-xs' %>
              <% if @current_user_role == AppConstants::ADMIN || @current_user_role == AppConstants::TEAM_LEADER%>
                  <%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/forms/index.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Froms</h2>
    <% if @current_user_role == AppConstants::ADMIN || @current_user_role == AppConstants::TEAM_LEADER %>
        <%= link_to 'New Form', new_form_path , class: 'btn btn-primary pull-right' %>
     <% end %>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <table class="table table-striped table-responsive" id="example">
      <thead>
      <tr>
        <th>Department</th>
        <th>Category</th>
        <th>Date started</th>
        <th>Date completed</th>
        <th>Summary of Problem</th>
        <th>Impact</th>
        <th>Applicable to Other Areas</th>
        <th>Solution Applied</th>
        <th>Level</th>
        <th>Created By</th>
        <th>Updated By</th>
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>
      <% @forms.each do |form| %>
          <tr>
            <td><%= form.department %></td>
            <td><%= form.category %></td>
            <td><%= form.date_started %></td>
            <td><%= form.date_completed %></td>
            <td><%= form.summary_of_problem %></td>
            <td><%= form.impact %></td>
            <td><%= form.applicable_to_other_areas %></td>
            <td><%= form.solution_applied %></td>
            <td><%= form.category_level %></td>
            <td><% id =form.user_id %><% @user = User.find_by_id( id ) %><%= @user.first_name %></td>
            <!--<td><% id =form.updated_by %><% @user = User.find_by_id( id ) %><%#= @user.first_name %></td>-->
            <td><%= form.updated_by %></td>
            <td>
              <%= link_to 'Edit', edit_form_path(form), class: 'btn btn-info btn-xs' %>
              <% if @current_user_role == AppConstants::ADMIN || @current_user_role == AppConstants::TEAM_LEADER%>
                <%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/forms/low_forms.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Froms</h2>
    <% if @current_user_role == AppConstants::ADMIN || @current_user_role == AppConstants::TEAM_LEADER %>
        <%= link_to 'New Form', new_form_path , class: 'btn btn-primary pull-right' %>
    <% end %>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <table class="table table-striped table-responsive" id="example">
      <thead>
      <tr>
        <th>Department</th>
        <th>Category</th>
        <th>Date started</th>
        <th>Date completed</th>
        <th>Summary of Problem</th>
        <th>Impact</th>
        <th>Applicable to Other Areas</th>
        <th>Solution Applied</th>
        <th>Level</th>
        <th>Created By</th>
        <th>Updated By</th>
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>
      <% @forms.each do |form| %>
          <tr>
            <td><%= form.department %></td>
            <td><%= form.category %></td>
            <td><%= form.date_started %></td>
            <td><%= form.date_completed %></td>
            <td><%= form.summary_of_problem %></td>
            <td><%= form.impact %></td>
            <td><%= form.applicable_to_other_areas %></td>
            <td><%= form.solution_applied %></td>
            <td><%= form.category_level %></td>
            <td><% id =form.user_id %><%=  User.find_by_id( id ).first_name %></td>
            <td><% id =form.updated_by %><%=  User.find_by_id( id ).first_name || 0 %></td>
            <td>
              <%= link_to 'Edit', edit_form_path(form), class: 'btn btn-info btn-xs' %>
              <% if @current_user_role == AppConstants::ADMIN || @current_user_role == AppConstants::TEAM_LEADER%>
                  <%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/forms/medium_forms.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Froms</h2>
    <% if @current_user_role == AppConstants::ADMIN || @current_user_role == AppConstants::TEAM_LEADER %>
        <%= link_to 'New Form', new_form_path , class: 'btn btn-primary pull-right' %>
    <% end %>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <table class="table table-striped table-responsive" id="example">
      <thead>
      <tr>
        <th>Department</th>
        <th>Category</th>
        <th>Date started</th>
        <th>Date completed</th>
        <th>Summary of Problem</th>
        <th>Impact</th>
        <th>Applicable to Other Areas</th>
        <th>Solution Applied</th>
        <th>Level</th>
        <th>Created By</th>
        <th>Updated By</th>
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>
      <% @forms.each do |form| %>
          <tr>
            <td><%= form.department %></td>
            <td><%= form.category %></td>
            <td><%= form.date_started %></td>
            <td><%= form.date_completed %></td>
            <td><%= form.summary_of_problem %></td>
            <td><%= form.impact %></td>
            <td><%= form.applicable_to_other_areas %></td>
            <td><%= form.solution_applied %></td>
            <td><%= form.category_level %></td>
            <td><% id =form.user_id %><%=  User.find_by_id( id ).first_name %></td>
            <td><% id =form.updated_by %><%=  User.find_by_id( id ).first_name || 0 %></td>
            <td>
              <%= link_to 'Edit', edit_form_path(form), class: 'btn btn-info btn-xs' %>
              <% if @current_user_role == AppConstants::ADMIN || @current_user_role == AppConstants::TEAM_LEADER%>
                  <%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/forms/new.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>New From</h2>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">

    <%= render 'form', form: @form %>

  </div>
</div>

app/views/forms/show.html.erb
<div class="x_panel">
  <div class="x_content">

    <p>
      <strong>Posted By:</strong>
      <%= @form.user.first_name %>
    </p>

    <p>
      <strong>Department:</strong>
      <%= @form.department %>
    </p>

    <p>
      <strong>Category:</strong>
      <%= @form.category %>
    </p>

    <p>
      <strong>Date started:</strong>
      <%= @form.date_started %>
    </p>

    <p>
      <strong>Date completed:</strong>
      <%= @form.date_completed %>
    </p>

    <p>
      <strong>Level:</strong>
      <%= @form.category_level %>
    </p>

    <p>
      <strong>Summary of Problem:</strong>
      <%= @form.summary_of_problem %>
    </p>

    <p>
      <strong>Impact:</strong>
      <%= @form.impact %>
    </p>

    <p>
      <strong>Applicable to Other Areas:</strong>
      <%= @form.applicable_to_other_areas %>
    </p>

    <p>
      <strong>Solution Applied:</strong>
      <%= @form.solution_applied %>
    </p>

  </div>
</div>
<%= link_to 'Back', forms_path , class: 'btn btn-primary pull-left' %>